---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: check-image-keyless
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  rules:
    - name: check-image-keyless
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/thomasvitale/band-service:*"
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/ThomasVitale/band-service/.github/workflows/commit-stage.yml@refs/*"
              issuer: "https://token.actions.githubusercontent.com"
