apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: band-service
spec:
  template:
    spec:
      containers:
        - name: band-service
          image: ghcr.io/thomasvitale/band-service
          ports:
            - containerPort: 8080
