apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: band-service
spec:
  template:
    spec:
      containers:
        - name: band-service
          image: ghcr.io/polarbookshop/band-service
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: '0.5'
              memory: '1Gi'
            limits:
              cpu: '2'
              memory: '2Gi'