apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: testing-pipeline
  labels:
    apps.kadras.io/pipeline: test
spec:
  params:
    - name: source-url
    - name: source-revision
    - name: source-subpath
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
        - name: source-subpath
          value: $(params.source-subpath)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
          - name: source-subpath
        steps:
          - name: test
            image: gradle
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              cd $(params.source-subpath)
              chmod +x ./gradlew
              ./gradlew test
