---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: band-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: band-service
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/ThomasVitale/band-service
      ref:
        branch: main
  build:
    env: 
      - name: BP_JVM_VERSION 
        value: "17.*"
  resources:
    limits:
      cpu: "1.5"
      memory: 756Mi
    requests:
      cpu: "0.1"
      memory: 756Mi
