---
apiVersion: app.kadras.io/v1alpha1
kind: Workload
metadata:
  name: band-service
  labels:
    app: band-service
spec:
  image: ghcr.io/thomasvitale/band-service
  application:
    framework: spring-boot
    language: java
