name: Commit Stage
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: thomasvitale/band-service
  VERSION: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Compile and test
        run: ./gradlew clean build
      
#      - name: SBOM vulnerability scanning
#        uses: aquasecurity/trivy-action@master
#        with:
#          scan-type: 'sbom'
#          scan-ref: 'build/reports/application.cdx.json'
#          format: 'sarif'
#          output: 'trivy-results-sbom.sarif'
#
#      - name: Upload vulnerability report
#        uses: github/codeql-action/upload-sarif@v3
#        if: success() || failure()
#        with:
#          sarif_file: 'trivy-results-sbom.sarif'
#          category: "sbom"

      - name: Package as OCI image
        run: ./gradlew bootBuildImage --imageName ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      
#      - name: OCI image vulnerability scanning
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
#          format: 'sarif'
#          output: 'trivy-results-oci-image.sarif'
#
#      - name: Upload vulnerability report
#        uses: github/codeql-action/upload-sarif@v3
#        if: success() || failure()
#        with:
#          sarif_file: 'trivy-results-oci-image.sarif'
#          category: "oci-image"

      - name: Login to Docker
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Publish OCI image
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  sign:
    name: Sign
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.0

      - uses: redhat-actions/podman-login@v1.7
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Fetch OCI image 
        run: podman pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Get OCI image digest
        id: image-info
        run: |
          image_digest=$(podman inspect --format='{{.Digest}}' ${REGISTRY}/${IMAGE_NAME}:${VERSION})
          echo $image_digest
          echo "IMAGE_DIGEST=${image_digest}" >> $GITHUB_ENV

      - name: Sign image
        run: |
          cosign sign --yes "${REGISTRY}/${IMAGE_NAME}@${IMAGE_DIGEST}"

      - name: Attest OCI image
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          subject-digest: ${{ env.IMAGE_DIGEST }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
