name: Commit Stage

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.editorconfig'
      - '.gitattributes'
      - '.gitignore'
      - '.sdkmanrc'
      - '*.adoc'
      - '*.png'
      - '*.md'
      - '*.txt'
      - 'catalog-info.yaml'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.yaml'
  pull_request:
    branches:
      - main

env:
  FLOX_DISABLE_METRICS: true
  REGISTRY: ghcr.io
  IMAGE: thomasvitale/band-service
  VERSION: ${{ github.sha }}

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Flox
        uses: flox/install-flox-action@9428713e8d3883274c334b4b95b8830beebd24d2 # v2.3.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Compile and test
        uses: flox/activate-action@410568008895a0f2e09a34bbd9523f8ef1f2d292 # v1.1.0
        with:
          command: task build

#      - name: Publish SBOM
#        uses: DependencyTrack/gh-upload-sbom@48feab3080ff9e8f51f4d21861d9fc914eb744f5 # v3.1.0
#        with:
#          serverHostname: ${{ secrets.DEPENDENCY_TRACK_HOSTNAME }}
#          apiKey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
#          projectName: ${{ github.event.repository.name }}
#          projectVersion: ${{ github.ref_name }}
#          projectTags: 'java,spring-boot'
#          bomFilename: "build/reports/cyclonedx/application.cdx.json"
#          autoCreate: true

  package:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Package
    runs-on: ubuntu-24.04
    needs: [build]
    permissions:
      artifact-metadata: write
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Flox
        uses: flox/install-flox-action@9428713e8d3883274c334b4b95b8830beebd24d2 # v2.3.0

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Login to Docker
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Build and publish AMD64 OCI image
        uses: flox/activate-action@410568008895a0f2e09a34bbd9523f8ef1f2d292 # v1.1.0
        with:
          command: task image:build:amd64 VERSION=${{ env.VERSION }}

      - name: Build and publish ARM64 OCI image
        uses: flox/activate-action@410568008895a0f2e09a34bbd9523f8ef1f2d292 # v1.1.0
        with:
          command: task image:build:arm64 VERSION=${{ env.VERSION }}

      - name: Build and publish multi-arch OCI image
        uses: flox/activate-action@410568008895a0f2e09a34bbd9523f8ef1f2d292 # v1.1.0
        with:
          command: task image:build VERSION=${{ env.VERSION }}

      - name: Sign OCI image
        uses: flox/activate-action@410568008895a0f2e09a34bbd9523f8ef1f2d292 # v1.1.0
        with:
          command: task image:sign VERSION=${{ env.VERSION }}

      - name: Read image digest
        id: digest
        uses: flox/activate-action@410568008895a0f2e09a34bbd9523f8ef1f2d292 # v1.1.0
        with:
          command: echo "IMAGE_DIGEST=$(skopeo inspect docker://${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }} | jq -r '.Digest')" >> $GITHUB_ENV

      - name: Attest OCI image
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          subject-digest: ${{ env.IMAGE_DIGEST }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
